name: Deploy to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # - name: Checkout code
            #   uses: actions/checkout@v2

            # - name: Set up Node.js
            #   uses: actions/setup-node@v2
            #   with:
            #       node-version: 18

            # - name: Install dependencies
            #   run: npm ci

            # - name: Build
            #   run: npm run build

            - name: Set up SSH ke/home/andrei
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SERVER_PRIVATE_KEY }}

            - name: Copy files to remote server
              run: |
                  ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "ls -all"

            # scp -r -P ${{ secrets.SERVER_PORT }} /dist/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/andrei/www/lavrenov.io/root/production/adventofcode/2023

            # - name: Add SSH keys
            #   run: |
            #       install -m 600 -D /dev/null ~/.ssh/id_rsa
            #       echo "${{ secrets.SERVER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            #       ssh-keyscan -H ${{ secrets.SERVER_HOST }} > ~/.ssh/known_hosts

            # - name: Copy to server
            #   run: ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"

        # - name: Deploy to server
        #   uses: appleboy/ssh-action@master
        #   with:
        #       host: ${{ secrets.SERVER_HOST }}
        #       username: ${{ secrets.SERVER_USERNAME }}
        #       key: ${{ secrets.SERVER_PRIVATE_KEY }}
        #       port: ${{ secrets.SERVER_PORT }}
        #       script: |
        #           rsync -avz --delete -e "ssh -p ${{ secrets.SERVER_PORT }} -i '${{ secrets.SERVER_PRIVATE_KEY }}'" dist/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/www/lavrenov.io/root/production/adventofcode/2023
