name: Create a release

on:
    push:
        tags:
            - '*'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Create release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      This is the release created for tag ${{ github.ref }}.
                  draft: false
                  prerelease: false
                  files: dist/*
